import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

function readWorkspaceFile(relativePath: string): string {
  return fs.readFileSync(path.join(rootDir, relativePath), "utf8");
}

function stripComments(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/(^|[^:])\/\/.*$/gm, "$1");
}

function parseQuotedStrings(source: string): string[] {
  return [...source.matchAll(/"([^"]+)"/g)].map((match) => match[1]);
}

function parseAppCommands(): string[] {
  const source = readWorkspaceFile("src-tauri/build.rs");
  const match = source.match(
    /const\s+APP_COMMANDS\s*:\s*&\[\s*&str\s*\]\s*=\s*&\[(?<body>[\s\S]*?)\]\s*;/
  );
  if (!match?.groups?.body) {
    throw new Error("Could not find APP_COMMANDS in src-tauri/build.rs");
  }
  return parseQuotedStrings(match.groups.body);
}

function parseGenerateHandlerCommands(): string[] {
  const source = readWorkspaceFile("src-tauri/src/lib.rs");
  const match = source.match(/tauri::generate_handler!\s*\[(?<body>[\s\S]*?)\]\s*\)/);
  if (!match?.groups?.body) {
    throw new Error("Could not find tauri::generate_handler![...] in src-tauri/src/lib.rs");
  }

  return stripComments(match.groups.body)
    .split(",")
    .map((entry) => entry.trim())
    .filter(Boolean)
    .map((entry) => {
      if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(entry)) {
        throw new Error(`Unexpected generate_handler entry: ${entry}`);
      }
      return entry;
    });
}

function parseAutogeneratedPermissionCommands(): string[] {
  const permissionsDir = path.join(rootDir, "src-tauri/permissions/autogenerated");
  const commands: string[] = [];

  for (const fileName of fs.readdirSync(permissionsDir).sort()) {
    if (!fileName.endsWith(".toml")) {
      continue;
    }
    const body = fs.readFileSync(path.join(permissionsDir, fileName), "utf8");
    const allowMatch = body.match(/commands\.allow\s*=\s*\[(?<body>[^\]]*)\]/);
    if (!allowMatch?.groups?.body) {
      continue;
    }
    commands.push(...parseQuotedStrings(allowMatch.groups.body));
  }

  return commands;
}

function commandToPermission(command: string): string {
  return `allow-${command.replaceAll("_", "-")}`;
}

function parseCapabilityCommandPermissions(): Set<string> {
  const capabilitiesDir = path.join(rootDir, "src-tauri/capabilities");
  const permissions = new Set<string>();

  for (const fileName of fs.readdirSync(capabilitiesDir).sort()) {
    if (!fileName.endsWith(".json")) {
      continue;
    }
    const capability = JSON.parse(fs.readFileSync(path.join(capabilitiesDir, fileName), "utf8")) as {
      permissions?: string[];
    };
    for (const permission of capability.permissions ?? []) {
      if (typeof permission === "string" && permission.startsWith("allow-")) {
        permissions.add(permission);
      }
    }
  }

  return permissions;
}

function formatList(values: string[]): string {
  return values.length === 0 ? "none" : values.map((value) => `  - ${value}`).join("\n");
}

function diffSets(left: Set<string>, right: Set<string>): string[] {
  return [...left].filter((value) => !right.has(value)).sort();
}

function duplicateValues(values: string[]): string[] {
  const seen = new Set<string>();
  const duplicates = new Set<string>();
  for (const value of values) {
    if (seen.has(value)) {
      duplicates.add(value);
    }
    seen.add(value);
  }
  return [...duplicates].sort();
}

function compareCommandSets(label: string, expectedCommands: string[], actualCommands: string[]): string[] {
  const expected = new Set(expectedCommands);
  const actual = new Set(actualCommands);
  const missing = diffSets(expected, actual);
  const extra = diffSets(actual, expected);

  if (missing.length === 0 && extra.length === 0) {
    return [];
  }

  return [
    `${label} is out of sync.`,
    `Missing:\n${formatList(missing)}`,
    `Extra:\n${formatList(extra)}`,
  ];
}

const generateHandlerCommands = parseGenerateHandlerCommands();
const appCommands = parseAppCommands();
const permissionCommands = parseAutogeneratedPermissionCommands();
const capabilityPermissions = parseCapabilityCommandPermissions();

const failures: string[] = [
  ...compareCommandSets("build.rs APP_COMMANDS", generateHandlerCommands, appCommands),
  ...compareCommandSets(
    "permissions/autogenerated command permissions",
    generateHandlerCommands,
    permissionCommands
  ),
];

const duplicateGroups: [string, string[]][] = [
  ["generate_handler", duplicateValues(generateHandlerCommands)],
  ["build.rs APP_COMMANDS", duplicateValues(appCommands)],
  ["permissions/autogenerated", duplicateValues(permissionCommands)],
].filter(([, duplicates]) => duplicates.length > 0);

for (const [label, duplicates] of duplicateGroups) {
  failures.push(`${label} contains duplicate commands:\n${formatList(duplicates)}`);
}

const missingCapabilityPermissions = generateHandlerCommands
  .map(commandToPermission)
  .filter((permission) => !capabilityPermissions.has(permission))
  .sort();

if (missingCapabilityPermissions.length > 0) {
  failures.push(
    `capabilities/*.json is missing command permissions:\n${formatList(missingCapabilityPermissions)}`
  );
}

if (failures.length > 0) {
  console.error(failures.join("\n\n"));
  process.exit(1);
}

console.log(`Tauri command chain is in sync (${generateHandlerCommands.length} commands).`);
